# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: '/home/runner/work/simple-java-maven-app/simple-java-maven-app/target/*'
    - name: Send greeting
      run: curl --location --request POST 'http://3.128.205.114:8081/api/v1/bom' --header 'X-Api-Key:XKCCVYXgea4QWCv8DOBj1Y3WyxkjuEHP' --form 'project="ae3014e4-0c87-4450-ba0c-2ccd17435bfb"' --form 'bom=@"/home/runner/work/simple-java-maven-app/simple-java-maven-app/target/sbom.xml"'

#    - name: Upload BOM to Dependency-Track
#      uses: DependencyTrack/gh-upload-sbom@v1.0.0
#      with:
#        projectname: 'demo'
#        projectversion: 'master'
#        serverhostname: 'ec2-3-16-70-13.us-east-2.compute.amazonaws.com'
#        apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
#        project: '71e6112d-62b9-4c6a-b8cd-c1b3185b7f98'
#        bomfilename: /home/runner/work/simple-java-maven-app/simple-java-maven-app/target/sbom.xml
# You may pin to the exact commit or the version.
  # uses: DependencyTrack/gh-upload-sbom@801995c917fdcc580f96275837bcbe6b46e5b159
#      uses: DependencyTrack/gh-upload-sbom@v1.0.0
#      with:
    # Dependency-Track hostname
#        serverhostname: ec2-18-189-143-172.us-east-2.compute.amazonaws.com
    # Dependency-Track port
#        port: 8080
    # Dependency-Track API key
 #       apikey: XKCCVYXgea4QWCv8DOBj1Y3WyxkjuEHP
 #       protocol: https
    # Project name in Dependency-Track
 #       projectname: demo
    # Project version in Dependency-Track
    #    projectversion: 2.7.4
    # Automatically create the project in Dependency-Track if it doesn't exist
 #       autocreate: true
    # Path and filename of the BOM
 #       bomfilename: /home/runner/work/simple-java-maven-app/simple-java-maven-app/target/sbom.xml

 #   - name: Update dependency graph
 #     uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
